name: .NET PR Tests
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'dotnet/**'

jobs:
  test:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Label PR (dotnet, c#, csharp)
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            dotnet
            c#
            csharp

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '6.0.x'

      - name: Run .NET Tests
        run: |
          cd dotnet
          dotnet test --verbosity normal